Fixup resource ids as brent/barnet harvesters were erroring
This was due to upstream id's being too short for our CKAN validation

ID's are now padded with 0's to ensure they meet a minimum length

Prior to this commit resources on upstream brent/barnet would raise
this error on ingestion:

2024-10-22 10:36:24,743 INFO  [ckanext.datapress_harvester.harvesters.mixins] Org 9d16bf37-e5ce-4abf-856f-8ab2f9917f42 exists
2024-10-22 10:36:24,762 INFO  [ckanext.harvest.harvesters.base] Package with GUID e1gd6 does not exist, let's create it
2024-10-22 10:36:24,776 ERROR [ckanext.harvest.harvesters.base] None - {'resources': [{'id': ['Invalid length for resource id']}]}
Traceback (most recent call last):
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/harvesters/base.py", line 291, in _create_or_update_package
    existing_package_dict = self._find_existing_package(package_dict)
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/harvesters/base.py", line 377, in _find_existing_package
    return p.toolkit.get_action('package_show')(
  File "/srv/app/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src/ckan/ckan/logic/action/get.py", line 1018, in package_show
    raise NotFound
ckan.logic.NotFound

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/app/src/ckanext-harvest/ckanext/harvest/harvesters/base.py", line 355, in _create_or_update_package
    new_package = p.toolkit.get_action(
  File "/srv/app/src/ckan/ckan/logic/__init__.py", line 551, in wrapped
    result = _action(context, data_dict, **kw)
  File "/srv/app/src/ckan/ckan/logic/action/create.py", line 200, in package_create
    raise ValidationError(errors)
ckan.logic.ValidationError: None - {'resources': [{'id': ['Invalid length for resource id']}]}